import express from 'express'
import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'
import { buildGraph, listByType } from './vaultParser.js'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const VAULT = path.resolve(__dirname, '..', '..', 'vault')
const PORT = 5175

const app = express()
app.use(express.json({ limit: '5mb' }))

// external sources registry — edit dashboard/sources.json to connect any local folder
// (incl. Google Drive for Desktop mounts: one entry per Google account)
function loadSources() {
  try {
    return JSON.parse(fs.readFileSync(path.resolve(__dirname, '..', 'sources.json'), 'utf-8'))
  } catch {
    return []
  }
}

function sourceFilePath(p) {
  // p looks like "src:<name>/<relpath>"
  const m = p.match(/^src:([^/]+)\/(.+)$/)
  if (!m) return null
  const src = loadSources().find((s) => s.name === m[1])
  if (!src) return null
  const full = path.resolve(src.path, m[2])
  if (!full.startsWith(path.resolve(src.path))) throw new Error('path escapes source')
  return full
}

// resolve a client-supplied relative path safely inside the vault
function vaultPath(rel) {
  const full = path.resolve(VAULT, rel)
  if (!full.startsWith(VAULT)) throw new Error('path escapes vault')
  return full
}

app.get('/api/graph', (req, res) => {
  res.json(buildGraph(VAULT, loadSources()))
})

app.get('/api/note', (req, res) => {
  try {
    const p = req.query.p
    if (p.startsWith('src:')) {
      const full = sourceFilePath(p)
      if (!full) throw new Error('unknown source')
      const content = full.endsWith('.md')
        ? fs.readFileSync(full, 'utf-8')
        : `*(external file — read-only in Hank OS)*\n\n**Local path:** \`${full}\`\n\nOpen it with its native app, or link it from a vault note with a normal markdown link.`
      return res.json({ path: p, content, readOnly: true })
    }
    const full = vaultPath(p)
    res.json({ path: p, content: fs.readFileSync(full, 'utf-8') })
  } catch (e) {
    res.status(404).json({ error: String(e.message || e) })
  }
})

app.put('/api/note', (req, res) => {
  try {
    if (String(req.body.path).startsWith('src:')) throw new Error('external sources are read-only')
    const full = vaultPath(req.body.path)
    if (!full.endsWith('.md')) throw new Error('only .md files')
    fs.mkdirSync(path.dirname(full), { recursive: true })
    fs.writeFileSync(full, req.body.content, 'utf-8')
    res.json({ ok: true })
  } catch (e) {
    res.status(400).json({ error: String(e.message || e) })
  }
})

app.get('/api/notes-by-type', (req, res) => {
  res.json(listByType(VAULT, req.query.type))
})

// Voice (or any) capture → timestamped Inbox note; the Gardener files it overnight
app.post('/api/capture', (req, res) => {
  try {
    const text = (req.body.text || '').trim()
    if (!text) throw new Error('empty capture')
    const d = new Date()
    const stamp = `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')} ${String(d.getHours()).padStart(2, '0')}${String(d.getMinutes()).padStart(2, '0')}`
    const title = text.split(/\s+/).slice(0, 6).join(' ').replace(/[<>:"/\\|?*#]/g, '')
    const rel = `00 Inbox/${stamp} ${title}.md`
    const body = `---\ncaptured: ${d.toISOString()}\nsource: ${req.body.source || 'voice'}\n---\n\n${text}\n`
    const full = vaultPath(rel)
    fs.mkdirSync(path.dirname(full), { recursive: true })
    fs.writeFileSync(full, body, 'utf-8')
    res.json({ ok: true, path: rel })
  } catch (e) {
    res.status(400).json({ error: String(e.message || e) })
  }
})

// Assemble a context pack for a note: the note + everything within 1 hop,
// written to 90 System/context-packs/ so a Claude Code session can start with full context.
app.post('/api/context-pack', (req, res) => {
  try {
    const rel = req.body.path
    const g = buildGraph(VAULT)
    const neighbors = new Set()
    for (const l of g.links) {
      if (l.source === rel) neighbors.add(l.target)
      if (l.target === rel) neighbors.add(l.source)
    }
    const read = (p) => fs.readFileSync(vaultPath(p), 'utf-8')
    const name = path.basename(rel, '.md')
    let pack = `# Context Pack: ${name}\n\n*Generated by Hank OS dashboard. Everything Claude Code needs to work on "${name}" — the note plus its direct connections.*\n\n## Focus note: ${rel}\n\n${read(rel)}\n`
    for (const n of neighbors) {
      pack += `\n---\n\n## Connected: ${n}\n\n${read(n)}\n`
    }
    pack += `\n---\n\n*Vault root: ${VAULT} — schema at 90 System/schema.md, index at 90 System/index.md. Follow CLAUDE.md rules.*\n`
    const outRel = `90 System/context-packs/${name}.md`
    const out = vaultPath(outRel)
    fs.mkdirSync(path.dirname(out), { recursive: true })
    fs.writeFileSync(out, pack, 'utf-8')
    res.json({
      ok: true,
      path: outRel,
      neighbors: neighbors.size,
      command: `claude "Read the context pack at 'vault/${outRel}' and help me build from it."`,
    })
  } catch (e) {
    res.status(400).json({ error: String(e.message || e) })
  }
})

// Gap Finder: domain pairs with zero cross-links + well-connected notes that never leave their domain
app.get('/api/gaps', (req, res) => {
  const g = buildGraph(VAULT)
  const domains = [...new Set(g.nodes.map((n) => n.domain))].filter((d) => d !== '90 System')
  const domainOf = Object.fromEntries(g.nodes.map((n) => [n.id, n.domain]))
  const crossCount = {}
  for (const l of g.links) {
    const a = domainOf[l.source], b = domainOf[l.target]
    if (a !== b) crossCount[[a, b].sort().join('|')] = (crossCount[[a, b].sort().join('|')] || 0) + 1
  }
  const gaps = []
  for (let i = 0; i < domains.length; i++)
    for (let j = i + 1; j < domains.length; j++) {
      const key = [domains[i], domains[j]].sort().join('|')
      if (!crossCount[key]) gaps.push({ a: domains[i], b: domains[j] })
    }
  const insular = g.nodes.filter(
    (n) =>
      n.domain !== '90 System' &&
      n.degree >= 2 &&
      g.links.every((l) => {
        const other = l.source === n.id ? l.target : l.target === n.id ? l.source : null
        return !other || domainOf[other] === n.domain
      })
  )
  res.json({ gaps, insular: insular.map((n) => ({ id: n.id, name: n.name, domain: n.domain, degree: n.degree })) })
})

// serve the built frontend when present (production mode)
const dist = path.resolve(__dirname, '..', 'dist')
if (fs.existsSync(dist)) {
  app.use(express.static(dist))
  app.get('*', (req, res) => res.sendFile(path.join(dist, 'index.html')))
}

app.listen(PORT, () => console.log(`Hank OS vault API on http://localhost:${PORT} (vault: ${VAULT})`))
